### ISSUE TITLE
miniz-sys: add support for using system-wide miniz

### ISSUE THREAD

**Issue by ignatenkobrain** [alexcrichton/flate2-rs#143]
In Fedora we unbundle all libraries and would like to not use bundled miniz.

There is no pkg-config, but simple `#include <miniz.h>` and `-lminiz` should work just fine.

**Comment by infinity0** [comment]
Alternatively, reimplement miniz in rust? 

I see rustc [already dropped miniz](https://github.com/rust-lang/rust/issues/41770) and there are a couple of alternatives:

https://github.com/alexchandel/miniz-rs
https://github.com/Frommi/miniz_oxide

The latter one even recreates the API of C-miniz.

**Comment by infinity0** [comment]
In Debian we just [patch away miniz and miniz_oxide_c_api](https://salsa.debian.org/rust-team/debcargo-conf/blob/master/src/flate2/debian/patches/disable-miniz.patch) to use zlib instead.

I suggested #181 as an alternative; I don't see the value of including either miniz or miniz_oxide_c_api in Debian or anywhere else really, when pretty much all systems already have a zlib, especially in light of issues like #142.

**Comment by joshtriplett** [comment]
flate2 now defaults to `miniz_oxide` rather than `miniz-sys`, and if you can count on system libraries then you're *more* likely to have zlib than miniz. I don't think there's much value in supporting a system miniz; even the `miniz-sys` feature is more-or-less deprecated and only exists for compatibility.

I think this can probably be closed.
