### ISSUE TITLE
GZDecoder fails to decode

### ISSUE THREAD

**Issue by kali** [alexcrichton/flate2-rs#23]
GzDecoder fails silently (and weirdly) on a file that gzcat decodes correctly.

The file is huge (way over 4GB) so I hope this is not a limitation of the underlying implementation.

Anyway, the file can be obtain here:
http://dumps.wikimedia.org/other/wikidata/20150608.json.gz 

and I just have a simple src/main.rs like this:

```rust
extern crate flate2;

fn main() {
    let mut input = ::flate2::read::GzDecoder::new(
        ::std::fs::File::open("wikidata-20150608.json.gz").unwrap()
    ).unwrap();
    ::std::io::copy(&mut input, &mut ::std::io::stdout()).unwrap();
}
```

with
 
```
[dependencies]
flate2 = "0.2.7"
```

The output shows a single line containing an opening square bracket (which is expected) but stop there instead of going on.

The file should be a huge json array, with a valid json object per line followed by a coma, a header line with an opening bracket and a matching closing line.

**Comment by alexcrichton** [comment]
Hm, interesting! It looks like that file is actually two gzip-compressed streams concatenated together, the first of which is just a `[` character and a newline, where the next is the data you're expecting. For example if you seek the file 22 bytes then decoding will succeed as you might expect.

You wouldn't happen to know how these files are generated, would you? I'm curious if this is a file format standard that I just haven't found yet!

**Comment by kali** [comment]
You're right, it's a concatenation of gzip files.

I think I found the generating scripts here:
https://github.com/wikimedia/operations-puppet/blob/production/modules/snapshot/files/dumpwikidatajson.sh

To be honest, it is unclear if doing so is legit, even if gzip manpage mentions it:
http://stackoverflow.com/questions/1143270/how-to-concat-two-or-more-gzip-files-streams

**Comment by alexcrichton** [comment]
Oh wow, nice find @kali! In this case, I think I'm going to close this issue in favor of https://github.com/alexcrichton/flate2-rs/issues/14. I'd prefer to keep the gzip decoders as low-level as possible instead of layering on top decoding multiple files at once. Unfortunately you can't actually decompress a stream of multiple concatenated gzip files due to #14 right now (extra bytes are read at the end), but once that's solved it should be easy enough for an application to check if the end of the stream is reached and if not just keep going!
