### ISSUE TITLE
Optional compression

### ISSUE THREAD

**Issue by mishun** [alexcrichton/flate2-rs#40]
Sometimes software ([minisat](https://github.com/niklasso/minisat) for example) uses optional compression: it checks if provided data file is correct gzip archive. If yes then it unpacks and reads it, if not --- just reads file as is. Zlib even has gzopen/gzdopen functions that supports this behaviour.

GzDecoder::new consumes stream in case of gzip header parsing error, so we are forced to reopen in case of file or to have big toubles in case of non-file. It would be nice to support optional compression in flate2 or at least get stream and readed bytes back in case of header parse error.

**Comment by alexcrichton** [comment]
Hm it does seem that zlib has some... interesting behavior with gz files. I've historically also seen how they support concatenated gzip streams being interpreted as one stream as well. I personally prefer to be more explicit about what's going on rather than hide that under the covers...

Along those lines, it looks like zlib mainly only supports this sort of operation with a file descriptor as a file as the backing storage? Along those lines couldn't this be done by using `seek` to go back to the beginning of a file in the case that the header wasn't parsed? You shouldn't need to relinquish ownership as you can hand in `&mut R` instead of just `R`.

It may also be prudent though to add the ability to get back out the initial stream when trying to parse a gz header

**Comment by mishun** [comment]
Seek will work for files, although it is even uglier because something simple with seek instead of reopen, like:
```Rust
    let mut reader = io::BufReader::new(try!(fs::File::open(path)));
    match GzDecoder::new(&mut reader) {
        Ok(gz) => { parse(gz) }

        Err(ref e) if e.kind() == io::ErrorKind::InvalidInput => {
            try!(reader.seek(SeekFrom::Start(0)));
            parse(reader)
        }

        Err(e) => { Err(e) }
    }
```
will not pass borrow check.

Also, it would be nice to be able to read in such way from pipes or stdin (like minisat do with zlib)

**Comment by alexcrichton** [comment]
Yeah you won't be able to seek on pipes but you can perhaps use some buffering to try to decode just the header of the stream to see if it's a gzip stream or not (the first two bytes should tell I believe).

You don't need to an an explicit layer of buffering yourself (as this library already does so), and this should also work fine with pipes as it just requires `R: Read`

**Comment by alexcrichton** [comment]
Ok I'm going to close this for now as I'd prefer the types in this library do what they say on the tin, and otherwise I think all the bits and pieces are there now to recover this if need be.
